services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./sessions:/app/.sessions
      - waha_data:/app/.media
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:3000/webhook/waha
      WHATSAPP_HOOK_EVENTS: message
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: barber_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barber
      POSTGRES_DB: barberdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  waha_data:
